//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecMasterApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquityDB
    {
        public int Security_Id { get; set; }
        public string Security_Name { get; set; }
        public string Security_Description { get; set; }
        public string Has_Position { get; set; }
        public string Is_Active_Security { get; set; }
        public string Lot_Size { get; set; }
        public string BBG_Unique_Name { get; set; }
        public string CUSIP { get; set; }
        public string ISIN { get; set; }
        public string SEDOL { get; set; }
        public string Bloomberg_Ticker { get; set; }
        public string Bloomberg_Unique_ID { get; set; }
        public string BBG_Global_ID { get; set; }
        public string Ticker_and_Exchange { get; set; }
        public string Is_ADR_Flag { get; set; }
        public string ADR_Underlying_Ticker { get; set; }
        public string ADR_Underlying_Currency { get; set; }
        public string Shares_Per_ADR { get; set; }
        public string IPO_Date { get; set; }
        public string Pricing_Currency { get; set; }
        public string Settle_Days { get; set; }
        public string Total_Shares_Outstanding { get; set; }
        public string Voting_Rights_Per_Share { get; set; }
        public string Average_Volume___20D { get; set; }
        public string Beta { get; set; }
        public string Short_Interest { get; set; }
        public string Return___YTD { get; set; }
        public string Volatility___90D { get; set; }
        public string PF_Asset_Class { get; set; }
        public string PF_Country { get; set; }
        public string PF_Credit_Rating { get; set; }
        public string PF_Currency { get; set; }
        public string PF_Instrument { get; set; }
        public string PF_Liquidity_Profile { get; set; }
        public string PF_Maturity { get; set; }
        public string PF_NAICS_Code { get; set; }
        public string PF_Region { get; set; }
        public string PF_Sector { get; set; }
        public string PF_Sub_Asset_Class { get; set; }
        public string Country_of_Issuance { get; set; }
        public string Exchange { get; set; }
        public string Issuer { get; set; }
        public string Issue_Currency { get; set; }
        public string Trading_Currency { get; set; }
        public string BBG_Industry_Sub_Group { get; set; }
        public string Bloomberg_Industry_Group { get; set; }
        public string Bloomberg_Sector { get; set; }
        public string Country_of_Incorporation { get; set; }
        public string Risk_Currency { get; set; }
        public string Open_Price { get; set; }
        public string Close_Price { get; set; }
        public string Volume { get; set; }
        public string Last_Price { get; set; }
        public string Ask_Price { get; set; }
        public string Bid_Price { get; set; }
        public string PE_Ratio { get; set; }
        public string Dividend_Declared_Date { get; set; }
        public string Dividend_Ex_Date { get; set; }
        public string Dividend_Record_Date_ { get; set; }
        public string Dividend_Pay_Date { get; set; }
        public string Dividend_Amount { get; set; }
        public string Frequency { get; set; }
        public string Dividend_Type { get; set; }
    }
}
